siteTitle="Python in Visual Studio Code"
linkPrefix="/pythonVSCodeDocs"
docPages = [
  "/docs/jupyter/",
  "/docs/jupyter_getting-started/",
  "/docs/jupyter_prerequisites/",
  "/docs/jupyter_examples/"
]