siteTitle="Python in Visual Studio Code"
linkPrefix="/pythonVSCodeDocs"
docPages = [
  "/docs/python-path/",
  "/docs/autocomplete/",
  "/docs/formatting/",
  "/docs/linting/",
  "/docs/debugging/",
  "/docs/debugging_capture-user-input/",
  "/docs/debugging_terminal-console-apps/",
  "/docs/debugging_library-functions/",
  "/docs/debugging_google-app-engine/",
  "/docs/debugging_remote-debugging/",
  "/docs/debugging_debugging-nosetests/",
  "/docs/debugging_debugging-pytest/",
  "/docs/debugging_debugging-flask/",
  "/docs/debugging_sudo-root-privileges/",
  "/docs/unittests/",
  "/docs/unittests_more-options/",
  "/docs/unittests_unittest-framework/",
  "/docs/unittests_pytest-framework/",
  "/docs/unittests_nose-framework/",
  "/docs/refactoring/",
  "/docs/refactoring_rename/",
  "/docs/refactoring_extract-variables/",
  "/docs/refactoring_extract-method/",
  "/docs/refactoring_sort-imports/",
  "/docs/jupyter/",
  "/docs/jupyter_getting-started/",
  "/docs/jupyter_prerequisites/",
  "/docs/jupyter_configuration/",
  "/docs/jupyter_examples/",
  "/docs/miscellaneous/",
  "/docs/contribution/",
  "/docs/troubleshooting/",
  "/docs/troubleshooting_debugger/",
  "/docs/troubleshooting_virtual-environments/",
  "/docs/troubleshooting_linting/",
  "/docs/troubleshooting_formatting/",
  "/docs/troubleshooting_intellisense/",
  "/docs/troubleshooting_jupyter/",
  "/docs/roadmap/"
]